# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * 1-5"
    - cron: "30 05 * * 0,6"
jobs:
  
  build:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      
      - name: Get Postman files
        uses: actions/checkout@v6

      - name: Setup node.js
        uses: actions/setup-node@v6
        
      - name: Setup newman + html reporter
        shell: bash
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra
        
      - name: Run tests and get report
        shell: bash
        run: 'newman run Trello.postman_collection.json --environment Trello_Environment.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export report.html' 
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: "*.html"