
name: CI

on:
  workflow_dispatch:
    inputs:
        environment:
            required: true
            type: choice
            description: "Choose environment for run"
            default: 'Test'
            options: 
              - Test
              - Prod
        os_pick:
            required: true
            type: choice
            description: "Choose OS for run"
            default: 'ubuntu-latest'
            options: 
              - Ubuntu
              - Windows
              # - macos
              
  schedule:
    - cron: "30 15 * * 1-5"
    - cron: "30 05 * * 0,6"
jobs:
  
  build:
    
    runs-on: ${{ inputs.os_pick == 'Windows' && 'windows-latest' || 'ubuntu-latest' }}
    
    env:
      POSTMAN_ENV_FILE: ${{ inputs.environment == 'Prod' && 'Prod_Environment.postman_environment.json' || 'Test_Environment.postman_environment.json' }}
      # shell_env: ${{ inputs.os_pick == 'Windows' && 'cmd' || 'bash' }}

    steps:
      
      - name: Get Postman files
        uses: actions/checkout@v6
      
      - name: Use selected environment file
        shell: cmd
        run: echo "Environment selected -> ${{ env.POSTMAN_ENV_FILE }} on ${{ runner.os }}"

      - name: Setup node.js
        uses: actions/setup-node@v6
        
      - name: Setup newman + html reporter
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra
        
      - name: Run tests and get report
        env:
          trello_key: ${{ secrets.TRELLO_KEY }}
          trello_token: ${{ secrets.TRELLO_TOKEN }}
        # run: 'newman run Trello.postman_collection.json --environment ${{ env.POSTMAN_ENV_FILE }} --env-var "key=$trello_key" --env-var "token=$trello_token" -r cli,htmlextra --reporter-htmlextra-export report.html' 
        run: >
          newman run Trello.postman_collection.json 
          --environment "${{ env.POSTMAN_ENV_FILE }}" 
          --env-var "key=$trello_key" 
          --env-var "token=$trello_token" 
          -r cli,htmlextra 
          --reporter-htmlextra-export report.html
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: "*.html"
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.mail.ru
          server_port: 465
          from: '${{secrets.EMAIL_SENDER}}' 
          to: ${{secrets.EMAIL_SENDER}}
          subject: Github Actions job result
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          attachments: report.html
          body: Postman collection report attached - ${{github.repository}}
          
      - name: Send report to Telegram
        uses: BorisTestov/tg_sender_action@latest
        env:
          TG_SENDER_TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_SENDER_TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_SENDER_PAYLOAD_FILE_PATH: report.html
          TG_SENDER_PAYLOAD_MESSAGE: "Postman collection report attached"