# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "30 15 * * 1-5"
    - cron: "30 05 * * 0,6"
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Get Postman files
        uses: actions/checkout@v6

      - name: Setup node.js
        uses: actions/setup-node@v6

      - name: Setup newman + html reporter
        run: |
            npm install -g newman
            npm install -s newman-reporter-htmlextra
        
      - name: Get report
        run: |
          newman run Trello.postman_collection.json \
          --environment "Trello Environment.postman_environment.json" \
          -r htmlextra \
          --reporter-htmlextra-export report.html